// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: server/proto/articleRank/article.proto

package articleRank

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArticleRankService_GetArticleRank_FullMethodName = "/articleRank.ArticleRankService/GetArticleRank"
)

// ArticleRankServiceClient is the client API for ArticleRankService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArticleRankServiceClient interface {
	GetArticleRank(ctx context.Context, in *GetArticleRankRequest, opts ...grpc.CallOption) (*GetArticleRankResponse, error)
}

type articleRankServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleRankServiceClient(cc grpc.ClientConnInterface) ArticleRankServiceClient {
	return &articleRankServiceClient{cc}
}

func (c *articleRankServiceClient) GetArticleRank(ctx context.Context, in *GetArticleRankRequest, opts ...grpc.CallOption) (*GetArticleRankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArticleRankResponse)
	err := c.cc.Invoke(ctx, ArticleRankService_GetArticleRank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleRankServiceServer is the server API for ArticleRankService service.
// All implementations must embed UnimplementedArticleRankServiceServer
// for forward compatibility.
type ArticleRankServiceServer interface {
	GetArticleRank(context.Context, *GetArticleRankRequest) (*GetArticleRankResponse, error)
	mustEmbedUnimplementedArticleRankServiceServer()
}

// UnimplementedArticleRankServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArticleRankServiceServer struct{}

func (UnimplementedArticleRankServiceServer) GetArticleRank(context.Context, *GetArticleRankRequest) (*GetArticleRankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticleRank not implemented")
}
func (UnimplementedArticleRankServiceServer) mustEmbedUnimplementedArticleRankServiceServer() {}
func (UnimplementedArticleRankServiceServer) testEmbeddedByValue()                            {}

// UnsafeArticleRankServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticleRankServiceServer will
// result in compilation errors.
type UnsafeArticleRankServiceServer interface {
	mustEmbedUnimplementedArticleRankServiceServer()
}

func RegisterArticleRankServiceServer(s grpc.ServiceRegistrar, srv ArticleRankServiceServer) {
	// If the following call pancis, it indicates UnimplementedArticleRankServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArticleRankService_ServiceDesc, srv)
}

func _ArticleRankService_GetArticleRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleRankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleRankServiceServer).GetArticleRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleRankService_GetArticleRank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleRankServiceServer).GetArticleRank(ctx, req.(*GetArticleRankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArticleRankService_ServiceDesc is the grpc.ServiceDesc for ArticleRankService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArticleRankService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "articleRank.ArticleRankService",
	HandlerType: (*ArticleRankServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArticleRank",
			Handler:    _ArticleRankService_GetArticleRank_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/proto/articleRank/article.proto",
}
