services:
  nicofile-redis:
    image: redis:7.0.12
    container_name: nicofile-redis
    ports:
      - "6380:6380"
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /etc/redis/redis.conf
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
  nicofile_kafka:
    image: bitnami/kafka:3.9.0
    container_name: nicofile-kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller  # 启用 KRaft 模式
      - KAFKA_CFG_NODE_ID=1  # 节点 ID
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER  # 指定控制器监听器名称
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093  # 投票者配置
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093  # 监听器
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092  # 对外暴露的地址
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes  # 允许明文通信
    volumes:
      - ./kafka:/bitnami/kafka
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
